"""Elaboration engine -- the Python port of ``Genesis2::UniqueModule``.

This is a behavioural port of ``Genesis2/PerlLibs/Genesis2/UniqueModule.pm``
covering construction (``new``/``new_as_son``/``new_as_clone``), the
parameter machinery (``define_param``/``parameter``/``get_param``/
``override_param``), the hierarchy / instantiation API
(``unique_inst``/``unique_inst_param``/``clone_inst``/``ununique_inst``/
``synonym``), name and path getters, and Verilog emission.

Several Perl-side details (e.g. exact priority handling, Data::Dumper
ordering for hashing, OUTFILE handle sharing across synonyms) are
simplified or reinterpreted relative to the Perl original.
"""

from __future__ import annotations

import copy
import hashlib
import io
import pprint
import re
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple

from . import cache, hashing, reporting
from .config_handler import PRIORITY_LABELS, Priority, priority_label
from .reporting import ElaborationError, ParameterError

if TYPE_CHECKING:  # pragma: no cover
    from .manager import Manager
    from .template.runtime import StrCallable


# Parameter "state" values, mirroring the Perl flag triplet.
STATE_DEFINED = "DEFINED"
STATE_FORCED = "FORCED"
STATE_OVERRIDDEN = "OVERRIDDEN"

# Value-column cap for the --param-footer table, in characters.
_PARAM_FOOTER_VALUE_WIDTH = 32


def _subtree_tag(subtree_sig) -> str:
    # subtree_sig is a sorted tuple of hashable triples; repr-then-sha256
    # is enough to discriminate, no need to canonicalise further.
    if not subtree_sig:
        return ""
    return "::sub::" + hashlib.sha256(repr(subtree_sig).encode()).hexdigest()


def _comparable_lines(text: str, style) -> List[str]:
    """Lines of ``text`` minus blanks and comments, for structural diffing.

    ``style`` is ``manager.output_comment``: a ``str`` line-comment prefix,
    or an ``(open, close)`` tuple whose whole-line delimiters bracket block
    comments (the ``to_verilog`` banner shape). Mirrors the comment/blank
    skipping in Perl ``compare_generated_files`` (UniqueModule.pm:3170).
    """
    out: List[str] = []
    if isinstance(style, tuple):
        open_d, close_d = (d.strip() for d in style)
        in_block = False
        for line in text.splitlines():
            stripped = line.strip()
            if in_block:
                if stripped == close_d:
                    in_block = False
                continue
            if stripped == open_d:
                in_block = True
                continue
            if stripped:
                out.append(line)
    else:
        for line in text.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith(style):
                out.append(line)
    return out


def _param_provenance(entry: Dict[str, Any]) -> str:
    """Name the configuration source a resolved parameter's value came from.

    ``state`` is authoritative for ``FORCED`` -- ``force_param`` is what pins
    the value. Otherwise the stored ``priority`` names the winning source.
    ``OVERRIDDEN`` with no recorded priority means a ConfigHandler that does
    not report one, so say so rather than calling the value a default.
    """
    prio = int(entry.get("priority") or 0)
    if entry.get("state") == STATE_FORCED:
        return PRIORITY_LABELS[int(Priority.IMMUTABLE)]
    if entry.get("state") == STATE_OVERRIDDEN and prio <= int(Priority.DECLARATION):
        return "external configuration (source not recorded)"
    return priority_label(prio)


class UniqueModule:
    """Base class for elaborated hardware modules.

    Canonical shared state (MODULE_CACHE, MODULE_NAME_NUM_DERIVS,
    OUTFILE_CONTENT_CACHE) lives in :mod:`cache`; access it directly
    rather than via class attributes.
    """

    # Default Verilog extension for direct subclasses (tests, library use)
    # that aren't generated by the .vpy emitter. Generated classes override
    # this via ``template/emitter._header`` based on the input extension.
    _OUTPUT_SUFFIX: str = ".v"

    # ------------------------------------------------------------------ ctor
    def _init_defaults(
        self, manager: "Manager", parent: Optional["UniqueModule"]
    ) -> None:
        # Single source of truth for the instance attribute set; called by
        # __init__ and both alt-ctors. Add new fields here.
        self._manager = manager
        self._parent = parent
        self._sub_instances: Dict[str, UniqueModule] = {}

        cls_name = type(self).__name__
        self._module_name: str = cls_name           # base (class) name
        self._unique_module_name: str = cls_name    # filename / Verilog name
        self._instance_name: str = cls_name         # default to class name

        self._params: Dict[str, Dict[str, Any]] = {}
        # Perl's priority register: writes are allowed until the body has
        # run, and not while a child elaborates (UniqueModule.pm:833, 1246).
        self._params_open: bool = True
        self._synonyms: List[str] = []
        self._clone_of: Optional[UniqueModule] = None

        # Verilog output buffer, allocated lazily by :meth:`execute`.
        self._outfile_handle: Optional[io.StringIO] = None
        self._outfile_name: Optional[str] = None

    def __init__(self, manager: "Manager") -> None:
        # Root constructor (mirrors Perl ``new`` at UniqueModule.pm:130).
        self._init_defaults(manager, None)
        cache.register(self._unique_module_name, self)

    # -- alternate constructors -----------------------------------------
    @classmethod
    def _new_as_son(cls, parent: "UniqueModule") -> "UniqueModule":
        """Create a child instance under ``parent`` (Perl ``new_as_son``)."""
        self = cls.__new__(cls)
        self._init_defaults(parent._manager, parent)
        return self

    @classmethod
    def _new_as_clone(
        cls, src: "UniqueModule", parent: "UniqueModule"
    ) -> "UniqueModule":
        """Clone ``src`` under ``parent`` (Perl ``new_as_clone``).

        Parameter dict is deep-copied; the generated Verilog file is
        *shared* via the synonym list so both names resolve to the same
        cached output.
        """
        self = cls.__new__(cls)
        self._init_defaults(parent._manager, parent)

        self._module_name = src._module_name
        # Synonym semantics: clone reuses src's unique module name so that
        # only one Verilog file is emitted.
        self._unique_module_name = src._unique_module_name
        self._instance_name = src._instance_name

        self._params = copy.deepcopy(src._params)
        # A clone takes no parameters (UniqueModule.pm:314-326).
        self._params_open = False
        self._synonyms = list(src._synonyms)
        self._clone_of = src
        # Don't share src's StringIO; clone emits leak into src and a renamed
        # flush would exfiltrate src's content. Lazy-alloc in emit() if needed.
        self._outfile_name = src._outfile_name
        return self

    # ----------------------------------------------------------- parameters
    def _check_params_open(self, method: str) -> None:
        if not self._params_open:
            raise ParameterError(
                f"{self._module_name}->{method}: Adding parameter definitions "
                f"not allowed at this point (the module has been elaborated)"
            )

    def _new_entry(
        self, name: str, default: Any, *, doc: Optional[str] = None,
        type: Optional[str] = None, declared: bool,  # noqa: A002
    ) -> Dict[str, Any]:
        entry = {
            "value": default,
            "default": default,
            "state": STATE_DEFINED,
            "priority": 0,
            "doc": doc,
            "type": type,
            # Perl's 'Used' state: set by a body declaration, not by a
            # parent's keyword; get_param needs it (UniqueModule.pm:2296).
            "declared": declared,
            # Perl's SeenAt levels: a second declaration at the same level is
            # fatal (UniqueModule.pm:2443-2452).
            "seen_declaration": False,
            "seen_forced": False,
        }
        self._params[name] = entry
        return entry

    def _declare(
        self, name: str, default: Any, doc: Optional[str], type: Optional[str],  # noqa: A002
    ) -> Dict[str, Any]:
        """The body's declaration of ``name``: creates the entry, or marks
        one a parent's keyword created as declared and refreshes its
        metadata (the keyword value outranks the default). A second
        declaration is fatal (UniqueModule.pm:2443-2452)."""
        self._check_params_open("define_param")
        if not re.fullmatch(r"\w+", name or ""):
            raise ParameterError(
                f"{self._module_name}->define_param: illegal parameter name {name!r} "
                "(alphanumeric and underscore only)"
            )
        entry = self._params.get(name)
        if entry is None:
            entry = self._new_entry(name, default, doc=doc, type=type, declared=True)
        elif entry["seen_declaration"]:
            raise ParameterError(
                f"{self._module_name}->define_param: Parameter {name} already "
                f"declared/seen at the same priority {Priority.DECLARATION.name}"
            )
        else:
            entry["declared"] = True
            entry["default"] = default
            if doc is not None:
                entry["doc"] = doc
            if type is not None:
                entry["type"] = type
        entry["seen_declaration"] = True
        return entry

    def define_param(
        self,
        name: str,
        default: Any = None,
        doc: Optional[str] = None,
        type: Optional[str] = None,  # noqa: A002 -- mirrors Perl flag name
        **flags: Any,
    ) -> None:
        """Register a parameter (Perl ``define_param`` ~UniqueModule.pm:387).

        A value a parent's keyword already set is kept; the default and the
        metadata are recorded. Declaring a name twice, or declaring after
        the body has run, is fatal. ``name`` must match ``\\w+``
        (Perl UniqueModule.pm:2015): a dotted name would collide with the
        ``-p PATH.NAME`` grammar.
        """
        entry = self._declare(name, default, doc, type)
        if "priority" in flags:
            entry["priority"] = flags["priority"]

    def parameter(
        self,
        name: str,
        default: Any = None,
        *,
        force: bool = False,
        doc: Optional[str] = None,
        min: Any = None,  # noqa: A002 -- public keyword, mirrors the Perl Min/Max/List names
        max: Any = None,  # noqa: A002
        step: Any = None,
        list: Any = None,  # noqa: A002
        opt: Optional[str] = None,
    ) -> Any:
        """Declarative shortcut (Perl ``parameter`` UniqueModule.pm:1981).

        Behavioural notes:

        - If ``name`` is unknown, register it.
        - If already overridden (by unique_inst's pre-elaboration override
          pass or a forced override), keep the existing value.
        - Otherwise consult the manager's config_handler.

        Optional kwargs (mirror Perl ``Name``/``Val``/``Force``/``Doc``/
        ``Min``/``Max``/``Step``/``List``/``Opt`` at UniqueModule.pm:1981):

        - ``force=True`` writes ``default`` at FORCED priority on this
          call and locks the param against future ``override_param``.
          Equivalent to a one-shot ``define_param`` + ``force_param``.
        - ``doc=`` updates the documentation string (Perl ``Doc``).
        - ``min``/``max``/``step``/``list`` register a range constraint
          (mutually exclusive: min/max/step XOR list). The resolved
          value is range-checked immediately. Subsequent
          ``override_param`` / ``force_param`` re-check.
        - ``opt`` (``'yes'``/``'no'``/``'try'``) is store-only metadata
          for forward-compat with Perl's unused-param tracking; no
          behaviour change today.

        Parameter values may be any Python value, but module dedup
        hashing, JSON-config roundtrip, and the ``list``/``min``/``max``
        constraints assume JSON-shaped values (scalars, lists, dicts of
        same). Custom Python objects bypass dedup and don't roundtrip
        to JSON.
        """
        if not force:
            self._declare(name, default, doc, None)
        elif name in self._params and doc is not None:
            self._params[name]["doc"] = doc

        # Register range constraint before resolution so range-check runs
        # against the final value. Validation order matches Perl's
        # param_range (UniqueModule.pm:582): min/max/step XOR list.
        if any(x is not None for x in (min, max, step, list)):
            # Rule 6: re-defining a range via parameter() is fatal (Perl:594-595).
            if self._params[name].get("range") is not None:
                raise ParameterError(
                    f"{self._module_name}->parameter: "
                    f"Re-definition of range for parameter {name!r}!"
                )
            self._set_range(
                name, min=min, max=max, step=step, list_=list
            )

        # Forced form: write at FORCED priority and skip cfg lookup
        # (Perl force_param: define_param at IMMUTABLE, UniqueModule.pm:479).
        if force:
            self.force_param(name, default)
            if doc is not None:
                self._params[name]["doc"] = doc
            self._range_check(name, self._params[name]["value"])
            if opt is not None:
                self._params[name]["opt"] = self._normalise_opt(opt)
            return self._params[name]["value"]

        if opt is not None:
            self._params[name]["opt"] = self._normalise_opt(opt)

        if self._params[name]["state"] in (STATE_OVERRIDDEN, STATE_FORCED):
            self._range_check(name, self._params[name]["value"])
            return self._params[name]["value"]

        cfg = self._manager.cfg_handler
        if cfg is not None:
            path = self._instance_path_segments()
            v, prio = cfg.get_configuration_with_priority(
                name, instance_path=path
            )
            # prio is None only when no source defines the name; an explicit
            # JSON null arrives as (None, EXTERNAL_PARAM_FILE) and applies.
            if prio is not None:
                self._params[name]["value"] = v
                self._params[name]["state"] = STATE_OVERRIDDEN
                self._params[name]["priority"] = prio
                self._range_check(name, v)
                return v
        self._range_check(name, self._params[name]["value"])
        return self._params[name]["value"]

    # ------------------------------------------- doc_param / param_range
    def doc_param(self, name: str, msg: str) -> None:
        """Late-bind documentation on an existing parameter.

        Mirrors Perl ``doc_param`` (UniqueModule.pm:558): errors if the
        parameter doesn't exist; emits a warning if doc is already set.
        """
        if name not in self._params:
            raise ParameterError(
                f"{self._module_name}->doc_param: "
                f"cannot document un-existing parameter {name!r}"
            )
        if self._params[name].get("doc") is not None:
            reporting.warning(
                f"{self._module_name}->doc_param: "
                f"Re-documentation of parameter {name!r}. Overwriting!"
            )
        self._params[name]["doc"] = msg

    def param_range(
        self,
        name: str,
        *,
        min: Any = None,  # noqa: A002 -- mirrors Perl Min/Max/List wiki names
        max: Any = None,  # noqa: A002
        step: Any = None,
        list_: Any = None,  # noqa: A002 -- "list" would shadow builtin
    ) -> None:
        """Late-bind a range constraint on an existing parameter.

        Mirrors Perl ``param_range`` (UniqueModule.pm:582): errors if
        the parameter doesn't exist; errors on re-definition of range.
        Range is checked against the param's current value immediately.
        """
        if name not in self._params:
            raise ParameterError(
                f"{self._module_name}->param_range: "
                f"cannot add range to un-existing parameter {name!r}"
            )
        if self._params[name].get("range") is not None:
            raise ParameterError(
                f"{self._module_name}->param_range: "
                f"Re-definition of range for parameter {name!r}!"
            )
        self._set_range(name, min=min, max=max, step=step, list_=list_)
        self._range_check(name, self._params[name]["value"])

    def _set_range(
        self,
        name: str,
        *,
        min: Any = None,  # noqa: A002
        max: Any = None,  # noqa: A002
        step: Any = None,
        list_: Any = None,
    ) -> None:
        """Install a range constraint dict on the param entry.

        Validates combination legality mirroring Perl param_range
        (UniqueModule.pm:621-670).
        """
        has_minmax = any(x is not None for x in (min, max, step))
        has_list = list_ is not None
        if has_minmax and has_list:
            raise ParameterError(
                f"{self._module_name}->parameter: cannot combine "
                f"min/max/step with list for parameter {name!r}"
            )
        if not has_list:
            # Rule 1: step requires min or max (Perl:633-641).
            if step is not None and min is None and max is None:
                raise ParameterError(
                    f"{self._module_name}: parameter {name!r}: "
                    f"range rule 'Step' not allowed unless combined with 'Min' or 'Max'"
                )
            # Rule 2: step != 0 (Perl:639-641).
            if step is not None and step == 0:
                raise ParameterError(
                    f"{self._module_name}: parameter {name!r}: "
                    f"range rule 'Step' of size zero not allowed"
                )
            # Rule 3: min <= max (Perl:644-653).
            if min is not None and max is not None and min > max:
                raise ParameterError(
                    f"{self._module_name}: parameter {name!r}: "
                    f"range rule 'Min'={min!r} must be less than or equal to 'Max'={max!r}"
                )
            # Rule 4: (max - min) integer multiple of step (Perl:656-670).
            if step is not None and min is not None and max is not None:
                steps = (max - min) / step
                if steps != int(steps):
                    raise ParameterError(
                        f"{self._module_name}: parameter {name!r}: "
                        f"range rule 'Max'={max!r} not an integer number of "
                        f"'Steps'={step!r} away from 'Min'={min!r}"
                    )
        if has_list:
            self._params[name]["range"] = {"list": list_}
        else:
            self._params[name]["range"] = {
                "min": min, "max": max, "step": step,
            }

    def _range_check(self, name: str, value: Any) -> None:
        """Raise ParameterError if value violates the param's range."""
        rng = self._params.get(name, {}).get("range")
        if rng is None or value is None:
            return
        if "list" in rng:
            if value not in rng["list"]:
                raise ParameterError(
                    f"{self._module_name}: parameter {name!r} value "
                    f"{value!r} not in allowed list {rng['list']!r}"
                )
            return
        lo, hi = rng.get("min"), rng.get("max")
        if lo is not None and value < lo:
            raise ParameterError(
                f"{self._module_name}: parameter {name!r} value "
                f"{value!r} below min {lo!r}"
            )
        if hi is not None and value > hi:
            raise ParameterError(
                f"{self._module_name}: parameter {name!r} value "
                f"{value!r} above max {hi!r}"
            )
        # Rule 5: step grid check (Perl:705-723).
        st = rng.get("step")
        if st is not None:
            if lo is not None:
                anchor_label, anchor_val, diff = "min", lo, value - lo
            else:
                anchor_label, anchor_val, diff = "max", hi, hi - value
            steps = diff / st
            if steps != int(steps):
                raise ParameterError(
                    f"{self._module_name}: parameter {name!r} value "
                    f"{value!r} not an integer number of steps={st!r} "
                    f"from {anchor_label}={anchor_val!r}"
                )

    @staticmethod
    def _normalise_opt(opt: str) -> str:
        """Normalise Perl ``Opt`` values: case-insensitive yes/no/try."""
        o = opt.strip().lower()
        if o not in {"yes", "no", "try"}:
            raise ParameterError(
                f"parameter opt={opt!r}: expected one of 'yes', 'no', 'try'"
            )
        return o

    def get_param(self, name: str) -> Any:
        """The value of a parameter the body declared. A name only a parent's
        keyword set is fatal (UniqueModule.pm:2296)."""
        if name not in self._params:
            raise ParameterError(
                f"Unknown parameter {name!r} on {self._module_name}"
            )
        if not self._params[name]["declared"]:
            raise ParameterError(
                f"{self._module_name}->get_param: Trying to extract the value of "
                f"a parameter that was never explicitly declared. Use "
                f"parameter({name!r}, default) to declare it"
            )
        return self._params[name]["value"]

    def override_param(self, name: str, value: Any) -> None:
        """A parent's keyword value (INHERITANCE priority). An unknown name
        is created undeclared; a forced value is kept (UniqueModule.pm:2406)."""
        self._check_params_open("override_param")
        if name not in self._params:
            self._new_entry(name, value, declared=False)
        if self._params[name]["state"] == STATE_FORCED:
            return
        self._params[name]["value"] = value
        self._params[name]["state"] = STATE_OVERRIDDEN
        self._params[name]["priority"] = int(Priority.INHERITANCE)
        self._range_check(name, value)

    def force_param(self, name: str, value: Any) -> None:
        """Forced override -- pinned, cannot be re-overridden. A second
        force of the same name is fatal (UniqueModule.pm:2443-2452)."""
        self._check_params_open("force_param")
        if name not in self._params:
            self._new_entry(name, value, declared=True)
        entry = self._params[name]
        if entry["seen_forced"]:
            raise ParameterError(
                f"{self._module_name}->force_param: Parameter {name} already "
                f"declared/seen at the same priority {Priority.IMMUTABLE.name}"
            )
        entry["seen_forced"] = True
        entry["declared"] = True
        entry["value"] = value
        entry["state"] = STATE_FORCED
        entry["priority"] = int(Priority.IMMUTABLE)
        self._range_check(name, value)

    def _lock_params(self) -> None:
        """Close the parameter store once the body has run (UniqueModule.pm:1246)
        and warn about every keyword the body never declared (:2183-2189)."""
        self._params_open = False
        for name, entry in self._params.items():
            if not entry["declared"]:
                self.warning(
                    f"Parameter '{name}' was passed to {self.get_instance_path()} "
                    f"but it was never actually declared/used in {self._instance_name}"
                )

    def get_mod_param_list(self) -> Dict[str, Any]:
        """Return ``{name: value}`` for all parameters (Perl :2691)."""
        return {k: v["value"] for k, v in self._params.items()}

    def list_params(self) -> List[str]:
        """Return a sorted list of parameter names.

        Distinct from :meth:`get_mod_param_list` (which keeps the
        ``{name: value}`` dict form). Mirrors Perl ``list_params``
        (UniqueModule.pm:515).
        """
        return sorted(self._params.keys())

    def exists_param(self, name: str) -> bool:
        """True iff the body declared ``name`` (Perl ``exists_param``,
        UniqueModule.pm:496: a parent's keyword alone does not count)."""
        return name in self._params and self._params[name]["declared"]

    def get_top_param(self, name: str) -> Any:
        """Return the value of parameter ``name`` on the top module.

        Mirrors Perl ``get_top_param`` (UniqueModule.pm:550).
        """
        return self.get_top().get_param(name)

    # ----------------------------------------------------------- hierarchy
    def _scoped_overrides_for(
        self, child_path: tuple[str, ...]
    ) -> Dict[str, Any]:
        """Collect the scoped overrides (``--parameter PATH.NAME=V`` and
        ``configure("PATH.NAME", v)``) addressed to ``child_path`` exactly.

        Empty dict when none apply or no cfg_handler is attached. Used
        pre-elaboration so the dedup hash reflects scoped overrides and
        the child's ``parameter()`` call returns the overridden value.
        """
        cfg = self._manager.cfg_handler
        if cfg is None:
            return {}
        return dict(cfg.scoped_overrides_for(child_path))

    def _scoped_subtree_signature(
        self, child_path: tuple[str, ...]
    ) -> tuple:
        """Return a hashable signature of every scoped override (CLI and
        ``.cfg``) whose instance path is rooted at ``child_path``.

        Used as a dedup discriminator: two instances at different paths
        share a unique module only if the same subtree overrides apply
        to both. Without this, ``parent_mod`` instances with no direct
        params but different descendant overrides would collapse onto one
        cached unique module before any descendant could observe its
        scoped override.
        """
        cfg = self._manager.cfg_handler
        if cfg is None:
            return ()
        scoped_db = cfg.scoped_db_snapshot()
        if not scoped_db:
            return ()
        n = len(child_path)
        # Re-key relative to child_path so two instances at different paths
        # but with structurally-identical subtree overrides still dedup.
        rel = []
        for (path, name), entry in scoped_db.items():
            if path[:n] == child_path:
                rel.append((path[n:], name, entry["value"]))
        return tuple(sorted(rel, key=lambda t: (t[0], t[1])))

    def _resolve_params(
        self, inst_name: str, overrides: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Materialise final parameter dict for an instantiation.

        We don't actually run the child's defaults until elaboration, but
        we *do* need a stable param dict for the dedup hash. Layers are:
        explicit kwargs (highest), then scoped CLI and ``.cfg`` overrides
        targeting this exact instance path. The child fills in untouched
        defaults once it elaborates.
        """
        child_path = self._instance_path_segments() + (inst_name,)
        merged = dict(self._scoped_overrides_for(child_path))
        merged.update(overrides)  # explicit kwargs win
        return merged

    def _guard_new_instance_name(self, inst_name: str, api: str) -> None:
        """Raise if ``inst_name`` is already registered under this parent.

        Called at entry to each instantiation API before any child is
        created. The transient-overwrite path inside ``unique_inst``
        (post-elaboration dedup via ``_clone_from_cached``) must NOT call
        this guard; only the public entry points do.

        Mirrors Perl ``UniqueModule.pm:1158`` and siblings.
        """
        if inst_name in self._sub_instances:
            raise ElaborationError(
                f"{api}: Instance -->{inst_name}<-- already exists in module "
                f"{self.get_instance_path()}"
            )

    def unique_inst(
        self, module_cls, inst_name: str, **params: Any
    ) -> "UniqueModule":
        """Instantiate ``module_cls`` with parameter-based dedup.

        ``module_cls`` may be a class object or a string naming a module
        class to be looked up via the Manager's generated-module registry
        (string form is what user .vpy code typically uses).

        Mirrors UniqueModule.pm:1060-1340, key cache check at ~:1218.
        Two-stage dedup: fast pre-elaboration check on explicit overrides,
        then a post-elaboration check on final parameter values so
        defaults-vs-explicit-equal-value calls collapse onto one module.
        """
        if isinstance(module_cls, str):
            module_cls = self._manager.resolve_module_class(module_cls)

        self._guard_new_instance_name(inst_name, "unique_inst")

        eff_pre = self._resolve_params(inst_name, params)
        child_path = self._instance_path_segments() + (inst_name,)
        subtree_sig = self._scoped_subtree_signature(child_path)
        sig_pre = hashing.sha256_param_signature(module_cls.__name__, eff_pre)
        subtree_tag = _subtree_tag(subtree_sig)
        pre_key = f"{module_cls.__name__}::{sig_pre}{subtree_tag}"

        cache_enabled = not self._manager.no_module_cache
        if cache_enabled and pre_key in cache.MODULE_CACHE:
            existing = cache.MODULE_CACHE[pre_key]
            return self._clone_from_cached(existing, inst_name)

        child = module_cls._new_as_son(self)
        child._instance_name = inst_name
        for k, v in eff_pre.items():
            child.override_param(k, v)

        n = cache.next_derivation(module_cls.__name__)
        unique_name = f"{module_cls.__name__}_unq{n}"
        child._unique_module_name = unique_name

        # Transient: post-dedup may discard `child` and overwrite this slot;
        # safe only because elaboration is single-threaded.
        self._sub_instances[inst_name] = child

        try:
            if cache_enabled:
                # Journal cache writes so post-dedup rollback is O(writes), not O(cache).
                with cache.journaled() as journal:
                    self._execute_child(child)

                    eff_post = child.get_mod_param_list()
                    sig_post = hashing.sha256_param_signature(
                        module_cls.__name__, eff_post
                    )
                    post_key = (
                        f"{module_cls.__name__}::post::{sig_post}{subtree_tag}"
                    )

                    if post_key in cache.MODULE_CACHE:
                        existing = cache.MODULE_CACHE[post_key]
                        cache.rollback_journal(*journal)
                        # Reclaim the wasted _unqN only if no nested unique_inst
                        # bumped the counter past it.
                        if cache.MODULE_NAME_NUM_DERIVS.get(module_cls.__name__) == n:
                            cache.MODULE_NAME_NUM_DERIVS[module_cls.__name__] = n - 1
                        return self._clone_from_cached(existing, inst_name)

                    cache.MODULE_CACHE[pre_key] = child
                    cache.MODULE_CACHE[post_key] = child
            else:
                self._execute_child(child)
        except Exception:
            if self._sub_instances.get(inst_name) is child:
                del self._sub_instances[inst_name]
            raise

        cache.register(unique_name, child)
        return child

    def _clone_from_cached(
        self, existing: "UniqueModule", inst_name: str
    ) -> "UniqueModule":
        """Return a clone of an already-elaborated module under ``inst_name``."""
        clone = type(existing)._new_as_clone(existing, self)
        clone._instance_name = inst_name
        self._sub_instances[inst_name] = clone
        return clone

    def unique_inst_param(
        self, module_cls, inst_name: str, **params: Any
    ) -> "UniqueModule":
        """Like :meth:`unique_inst` but unique name encodes the params."""
        if isinstance(module_cls, str):
            module_cls = self._manager.resolve_module_class(module_cls)

        self._guard_new_instance_name(inst_name, "unique_inst_param")

        eff = self._resolve_params(inst_name, params)
        child_path = self._instance_path_segments() + (inst_name,)
        subtree_sig = self._scoped_subtree_signature(child_path)
        subtree_tag = _subtree_tag(subtree_sig)
        sig = hashing.sha256_param_signature(module_cls.__name__, eff)
        cache_key = f"{module_cls.__name__}::param::{sig}{subtree_tag}"

        cache_enabled = not self._manager.no_module_cache
        if cache_enabled and cache_key in cache.MODULE_CACHE:
            return self._clone_from_cached(cache.MODULE_CACHE[cache_key], inst_name)

        child = module_cls._new_as_son(self)
        child._instance_name = inst_name
        for k, v in eff.items():
            child.override_param(k, v)

        # Non-scalar values collapse to a short hash to keep the emitted name a legal identifier.
        # Separator between key and value mirrors Perl _${abbrev}_${val} (UniqueModule.pm:2718).
        def _safe_pair(k: str, v: Any) -> str:
            raw = f"{k}_{v}"
            if re.fullmatch(r"\w+", raw):
                return raw
            digest = hashing.sha256_param_signature("", {k: v})[:8]
            return f"{k}_{digest}"

        suffix = "_".join(_safe_pair(k, eff[k]) for k in sorted(eff))
        unique_name = (
            f"{module_cls.__name__}_{suffix}" if suffix else module_cls.__name__
        )
        if subtree_sig:
            # On an override path the param suffix alone is ambiguous: two
            # same-param parents whose descendants carry different scoped
            # overrides must emit distinct files (Perl gen_override_path_ext,
            # UniqueModule.pm:1431/:2789 -- counter shared with unique_inst).
            unique_name += f"_unq{cache.next_derivation(module_cls.__name__)}"
        child._unique_module_name = unique_name

        self._sub_instances[inst_name] = child
        try:
            self._execute_child(child)
        except Exception:
            if self._sub_instances.get(inst_name) is child:
                del self._sub_instances[inst_name]
            raise

        # Cache after execute() so a raising .vpy body doesn't poison it.
        if cache_enabled:
            cache.MODULE_CACHE[cache_key] = child
        cache.register(unique_name, child)
        return child

    def clone_inst(
        self, src_inst: "UniqueModule | str", new_name: str
    ) -> "UniqueModule":
        """Duplicate ``src_inst`` (an instance, or its dotted instance path)
        under ``new_name``.

        Mirrors Perl ``clone_inst`` (UniqueModule.pm:1480): a clone is an
        instance-level alias only — same ``UniqueModuleName`` as the source,
        new ``InstanceName`` — and emits **no** additional Verilog file.
        The parent module's instantiation references the source's unique
        module name with the clone's instance name as the instance label.

        Mirrors the Perl antecessor-cycle guard (UniqueModule.pm:1521):
        if the source's ``UniqueModuleName`` matches ``self`` or any
        ancestor, raise rather than silently building a self-referential
        hierarchy.
        """
        self._guard_new_instance_name(new_name, "clone_inst")
        src_inst = self.get_instance_obj(src_inst)

        src_uname = src_inst._unique_module_name
        ancestor: Optional[UniqueModule] = self
        while ancestor is not None:
            if ancestor._unique_module_name == src_uname:
                raise ElaborationError(
                    f"{new_name}: Instance {self.get_instance_path()}: "
                    f"is trying to instantiate a clone of itself or its "
                    f"antecessor ({ancestor.get_instance_path()}) !"
                )
            ancestor = ancestor._parent
        child = type(src_inst)._new_as_clone(src_inst, self)
        child._instance_name = new_name
        self._sub_instances[new_name] = child
        return child

    def ununique_inst(
        self, module_cls, inst_name: str, **params: Any
    ) -> "UniqueModule":
        """Instantiate without uniquification: emit the module under its
        bare base name (no ``_unqN`` suffix).

        Mirrors Perl ``ununique_inst`` (UniqueModule.pm:1545): the whole
        point of this entry point is to keep the emitted file findable
        under the base name (typical use case: an ``analog`` module to be
        replaced by a hand-written macro at PNR).

        Second call with the **same** base name:
          - identical resolved params and identical scoped-subtree
            signature -> alias the previously elaborated instance under
            the new ``inst_name`` (Perl uses the same file).
          - differing resolved params, same subtree signature -> raise
            ``ElaborationError`` with a Perl-style message and both param
            dicts (the on-disk filename is global, so two distinct
            elaborations can't both keep the bare name).
          - differing subtree signatures -> re-elaborate under a temp name
            and compare the generated body (blank lines and comments
            ignored) against the previous generation; identical bodies
            reuse the previous file, divergence raises
            ``ElaborationError`` (mirrors Perl's optimistic-reuse guard at
            UniqueModule.pm:1642 and the compare/rename at :1674-1700).
        """
        if isinstance(module_cls, str):
            module_cls = self._manager.resolve_module_class(module_cls)

        self._guard_new_instance_name(inst_name, "ununique_inst")

        # Same scoped-override layering as unique_inst / unique_inst_param.
        eff = self._resolve_params(inst_name, params)
        base_name = module_cls.__name__
        child_path = self._instance_path_segments() + (inst_name,)
        subtree_sig = self._scoped_subtree_signature(child_path)

        # --no-module-cache forces a fresh elaboration here as well.
        existing = (
            None if self._manager.no_module_cache
            else cache.UNUNIQUE_REGISTRY.get(base_name)
        )
        if existing is not None:
            if subtree_sig != existing["subtree_sig"]:
                # Differing descendant scoped overrides: optimistic reuse
                # is unsafe -- re-elaborate and compare generated bodies.
                return self._reelaborate_ununique(
                    module_cls, inst_name, eff, base_name
                )
            if eff == existing["params"]:
                # Identical params: alias the previously emitted module.
                return self._clone_from_cached(existing["instance"], inst_name)
            raise ElaborationError(
                f"ununique_inst: Will generate two different UN-uniquified "
                f"{base_name} modules! "
                f"First call params: {existing['params']!r}; "
                f"second call params: {eff!r}"
            )

        child = module_cls._new_as_son(self)
        child._instance_name = inst_name
        for k, v in eff.items():
            child.override_param(k, v)
        # Bare base name (no _unqN) so synthesis tools find the file.
        child._unique_module_name = base_name

        self._sub_instances[inst_name] = child
        try:
            self._execute_child(child)
        except Exception:
            if self._sub_instances.get(inst_name) is child:
                del self._sub_instances[inst_name]
            raise
        # After execute() so a raising body doesn't poison the caches.
        cache.register(base_name, child)
        cache.UNUNIQUE_REGISTRY[base_name] = {
            "instance": child,
            "params": dict(eff),
            "subtree_sig": subtree_sig,
        }
        return child

    def _reelaborate_ununique(
        self,
        module_cls,
        inst_name: str,
        eff: Dict[str, Any],
        base_name: str,
    ) -> "UniqueModule":
        """Second ``ununique_inst`` for ``base_name`` on a different
        override path: re-elaborate under a temp name and compare with the
        previous UN-uniquified generation (Perl UniqueModule.pm:1613-1700).
        """
        child = module_cls._new_as_son(self)
        child._instance_name = inst_name
        for k, v in eff.items():
            child.override_param(k, v)
        # Perl uses base_tmp<rand(10000)>; a namespaced derivation counter
        # keeps temp names deterministic without disturbing the _unqN
        # numbering for base_name.
        n = cache.next_derivation(f"{base_name}::ununq_tmp")
        tmp_name = f"{base_name}_tmp{n}"
        child._unique_module_name = tmp_name
        self._sub_instances[inst_name] = child
        try:
            self._execute_child(child)
        except Exception:
            if self._sub_instances.get(inst_name) is child:
                del self._sub_instances[inst_name]
            raise

        suffix = type(child)._OUTPUT_SUFFIX
        tmp_file = f"{tmp_name}{suffix}"
        base_file = f"{base_name}{suffix}"
        if not self._compare_generated_files(
            tmp_file, base_file, {tmp_name: base_name}
        ):
            # Keep tmp_file in OUTFILE_CONTENT_CACHE so the user can diff
            # the two generations (Perl :1685 keeps the temp file too).
            raise ElaborationError(
                f"ununique_inst: Newly generated UN-uniquified {base_name} "
                f"does not match previous UN-uniquified generation! "
                f"Compare {tmp_file} and previously generated {base_file}"
            )
        # Bodies match: drop the temp entry and point the child at the
        # previously created module/file (Perl :1692-1700). Must be `del`,
        # not .pop() -- only __setitem__/__delitem__ are journaled for the
        # nested-inside-unique_inst case.
        del cache.OUTFILE_CONTENT_CACHE[tmp_file]
        child._unique_module_name = base_name
        child._outfile_name = base_file
        return child

    def _compare_generated_files(
        self, file_a: str, file_b: str, name_map: Dict[str, str]
    ) -> bool:
        """Structural equality of two cached generated files.

        Port of Perl ``compare_generated_files`` (UniqueModule.pm:3130):
        line-by-line comparison ignoring blank lines and comments, with a
        word-boundary ``name_map`` applied to ``file_a`` (temp -> base
        module names). ``file_b`` missing from the cache means its
        generation is still in flight (recursion) -> no match.
        """
        if file_a not in cache.OUTFILE_CONTENT_CACHE:
            raise ElaborationError(
                f"compare_generated_files: can't find {file_a} in the "
                f"output cache"
            )
        if file_b not in cache.OUTFILE_CONTENT_CACHE:
            return False
        style = getattr(self._manager, "output_comment", "//")
        lines_a = _comparable_lines(cache.OUTFILE_CONTENT_CACHE[file_a], style)
        lines_b = _comparable_lines(cache.OUTFILE_CONTENT_CACHE[file_b], style)
        for key in sorted(name_map):
            pat = re.compile(rf"(^|(?<=\W)){re.escape(key)}(?=\W|$)")
            lines_a = [pat.sub(name_map[key], ln) for ln in lines_a]
        return lines_a == lines_b

    def generate(self, module_cls, inst_name: str, **params: Any) -> "UniqueModule":
        """Perl-compat shortcut: dispatch to unique_inst or unique_inst_param.

        Selection follows the active ConfigHandler's ``unq_style``
        (set via the ``-unqstyle`` CLI flag, default ``'numeric'``).
        Mirrors Perl ``generate`` (UniqueModule.pm:1846).
        """
        cfg = self._manager.cfg_handler
        style = cfg.unq_style if cfg is not None else "numeric"
        if style == "param":
            return self.unique_inst_param(module_cls, inst_name, **params)
        return self.unique_inst(module_cls, inst_name, **params)

    def generate_w_name(
        self,
        base_module_name: str,
        gen_module_name: str,
        inst_name: str,
        **params: Any,
    ) -> "UniqueModule":
        """Create an instance using a freshly-named module class.

        Faithful port of Perl ``generate_w_name`` (UniqueModule.pm:1940):
        registers ``gen_module_name`` as a class-level synonym of
        ``base_module_name``, then calls :meth:`ununique_inst` so the
        emitted module's unique name is derived from the new name rather
        than the original base.
        """
        gen_cls = self._manager.synonym_class(base_module_name, gen_module_name)
        return self.ununique_inst(gen_cls, inst_name, **params)

    def synonym(self, name: str) -> None:
        """Record an alternate name for this module's generated Verilog."""
        if name in self._synonyms:
            return
        self._synonyms.append(name)
        cache.register(name, self)

        suffix = type(self)._OUTPUT_SUFFIX
        src_file = f"{self._unique_module_name}{suffix}"
        if src_file in cache.OUTFILE_CONTENT_CACHE:
            cache.OUTFILE_CONTENT_CACHE[f"{name}{suffix}"] = (
                cache.OUTFILE_CONTENT_CACHE[src_file]
            )

    def get_synonyms(self) -> List[str]:
        """Return a shallow copy of the synonym names registered on this module.

        Synonyms are alternate names under which the module's emitted Verilog
        is also registered in :data:`cache.OUTFILE_CONTENT_CACHE`. Use this
        accessor in tests instead of touching ``_synonyms`` directly.
        """
        return list(self._synonyms)

    # ----------------------------------------------------------- name/path
    def get_module_name(self) -> str:
        """The emitted (unique) module name, as Perl's ``get_module_name``."""
        return self._unique_module_name

    def get_unique_module_name(self) -> str:
        return self._unique_module_name

    def get_base_name(self) -> str:
        return self._module_name

    def get_instance_name(self) -> str:
        return self._instance_name

    # Short aliases mirroring Genesis2's exported user API.
    #
    # Each property returns a :class:`StrCallable` (str subclass whose
    # ``__call__`` returns self) so both attribute form (``obj.mname``)
    # and method-call form (``obj.mname()``) work on instances, matching
    # Perl's ``$obj->mname()`` and bare ``mname`` usage uniformly. The
    # bare-name forms inside .vpy bodies already used StrCallable via the
    # emitter prelude; Cluster F closes the gap on instances.
    @property
    def mname(self) -> "StrCallable":
        from .template.runtime import StrCallable
        return StrCallable(self._unique_module_name)

    @property
    def iname(self) -> "StrCallable":
        from .template.runtime import StrCallable
        return StrCallable(self._instance_name)

    @property
    def bname(self) -> "StrCallable":
        from .template.runtime import StrCallable
        return StrCallable(self._module_name)

    @property
    def sname(self) -> "StrCallable":
        """Source template name (pre-uniquification, pre-synonym).

        Mirrors Perl ``get_source_name`` (UniqueModule.pm:377): returns
        ``_synonym_for`` if the class was built by
        :meth:`Manager.synonym_class`; otherwise the base module name.
        """
        from .template.runtime import StrCallable
        return StrCallable(
            getattr(type(self), "_synonym_for", None) or self._module_name
        )

    def instantiate(self, **ports: Any) -> str:
        """Return a Verilog instance fragment: ``MName inst (.p(v), ...)``.

        With no port kwargs, returns ``MName inst`` so the user can supply
        the port list separately in the surrounding template text.
        """
        head = f"{self._unique_module_name} {self._instance_name}"
        if not ports:
            return head
        port_lines = ",\n  ".join(f".{k}({v})" for k, v in ports.items())
        return f"{head} (\n  {port_lines}\n)"

    def _instance_path_segments(self) -> tuple[str, ...]:
        """Return the full instance path as a tuple of segment names,
        from root to self. Used for hierarchical config lookups.
        """
        chain: List[str] = []
        node: Optional[UniqueModule] = self
        while node is not None:
            chain.append(node._instance_name)
            node = node._parent
        return tuple(reversed(chain))

    def get_instance_path(self) -> str:
        """Root-to-self instance names joined with ``.``, the form
        ``get_instance_obj`` and the config overrides take (UniqueModule.pm:1070)."""
        return ".".join(self._instance_path_segments())

    # ------------------------------------------------- sub-instance navigation
    def get_subinst(self, name: str) -> "UniqueModule":
        """Return the sub-instance named ``name``; raise if absent.

        Mirrors Perl ``get_subinst`` (UniqueModule.pm:760).
        """
        inst = self._sub_instances.get(name)
        if inst is None:
            raise ElaborationError(
                f"{self._module_name}->get_subinst: "
                f"Could not find subinst {name!r}"
            )
        return inst

    def exists_subinst(self, name: str) -> bool:
        """Return True iff a sub-instance named ``name`` exists.

        Mirrors Perl ``exists_subinst`` (UniqueModule.pm:780).
        """
        return name in self._sub_instances

    def get_subinst_array(self, pattern: str = "") -> List["UniqueModule"]:
        """Return sub-instances whose instance names match ``pattern``.

        Empty pattern matches all. Pattern is a Python regex (``re.search``
        semantics; differs from Perl regex dialect for advanced features).
        Order follows insertion (mirrors Perl ``SubInstanceList`` order;
        UniqueModule.pm:932).
        """
        out: List[UniqueModule] = []
        for name, inst in self._sub_instances.items():
            if not pattern or re.search(pattern, name):
                out.append(inst)
        return out

    def get_instance_obj(
        self, inst: "str | UniqueModule"
    ) -> "UniqueModule":
        """Resolve ``inst`` to a :class:`UniqueModule`.

        - A :class:`UniqueModule` passes through unchanged.
        - A dotted path ``"top.a.b"`` is walked from the top instance.

        Mirrors Perl ``get_instance_obj`` (UniqueModule.pm:1087); the path
        is what ``get_instance_path()`` returns.
        """
        if isinstance(inst, UniqueModule):
            return inst
        if not isinstance(inst, str):
            raise ElaborationError(
                f"{self._module_name}->get_instance_obj: "
                f"expected str or UniqueModule, got {type(inst).__name__}"
            )
        top = self.get_top()
        top_name = top.get_instance_name()
        if not re.fullmatch(rf"{re.escape(top_name)}(\.\w+)*", inst):
            raise ElaborationError(
                f"{self._module_name}->get_instance_obj: "
                f"{inst!r} is not a legal instance path under {top_name!r}"
            )
        stripped = re.sub(rf"^{re.escape(top_name)}\.?", "", inst)
        node: UniqueModule = top
        for tok in (stripped.split(".") if stripped else []):
            if tok not in node._sub_instances:
                raise ElaborationError(
                    f"{self._module_name}->get_instance_obj: "
                    f"cannot find subinst {tok!r} of {inst!r}"
                )
            node = node._sub_instances[tok]
        return node

    def search_subinst(
        self,
        *,
        start_from: "UniqueModule | str | None" = None,
        depth: int = 10000,
        reverse: bool = False,
        path_regex: Optional[str] = None,
        iname_regex: Optional[str] = None,
        mname_regex: Optional[str] = None,
        bname_regex: Optional[str] = None,
        sname_regex: Optional[str] = None,
        has_param_regex: "str | List[str] | None" = None,
        apply_map: Any = None,
    ) -> List["UniqueModule"]:
        """DFS the elaborated hierarchy from ``start_from`` (default: top)
        and filter results by the supplied regex filters and predicate.

        All regex filters AND-compose. An empty-string regex matches
        everything. ``apply_map`` is a callable applied last; instances
        for which it returns falsy are dropped.

        Mirrors Perl ``search_subinst`` (UniqueModule.pm:797). The kwarg
        names are snake_case (Perl wiki uses CamelCase: ``PathRegex``,
        ``INameRegex``, etc.); translate at the call site.
        """
        start = (
            self.get_instance_obj(start_from)
            if start_from is not None
            else self.get_top()
        )

        results: List[UniqueModule] = []

        def _dfs(node: "UniqueModule", d: int) -> None:
            if d >= 0 and not reverse:
                results.append(node)
            if d >= 1:
                for child in node._sub_instances.values():
                    _dfs(child, d - 1)
            if d >= 0 and reverse:
                results.append(node)

        _dfs(start, depth)

        def _match(regex: Optional[str], value: str) -> bool:
            return regex is None or regex == "" or re.search(regex, value) is not None

        def _has_param(node: "UniqueModule", patterns) -> bool:
            params = node.get_mod_param_list()
            pats = patterns if isinstance(patterns, list) else [patterns]
            for p in pats:
                if p == "":
                    continue
                if not any(re.search(p, pname) for pname in params):
                    return False
            return True

        filtered: List[UniqueModule] = []
        for n in results:
            if not _match(path_regex, n.get_instance_path()):
                continue
            if not _match(iname_regex, str(n.iname)):
                continue
            if not _match(mname_regex, str(n.mname)):
                continue
            if not _match(bname_regex, str(n.bname)):
                continue
            if not _match(sname_regex, str(n.sname)):
                continue
            if has_param_regex is not None and not _has_param(n, has_param_regex):
                continue
            if apply_map is not None and not apply_map(n):
                continue
            filtered.append(n)
        return filtered

    # ----------------------------------------------------- product-list DFS
    def get_prod_list_insts(
        self, synth_top: Optional[str]
    ) -> List[Tuple["UniqueModule", bool]]:
        """DFS the elaborated subinstance tree; return ``(inst, is_synth)``
        pairs in Perl ``UniqueModule.pm::_get_prod_list_insts`` order.

        ``synth_top`` is the **dotted** instance path that bounds the
        synth cone (``None`` matches Perl ``SynthTop=undef`` -> every
        instance is verif).  An instance is synth iff its dotted path
        equals ``synth_top`` or starts with ``synth_top + "."``.  The
        traversal yields each ``(outfile_name, is_synth)`` pair at most
        once: this is what lets Manager promote a file seen on both
        sides to ``synth_and_verif``.
        """
        results: List[Tuple[UniqueModule, bool]] = []
        synth_files: set[str] = set()
        verif_files: set[str] = set()
        self._collect_prod_list(results, synth_files, verif_files, "", synth_top)
        return results

    def _collect_prod_list(
        self,
        results: List[Tuple["UniqueModule", bool]],
        synth_files: set,
        verif_files: set,
        path: str,
        synth_top: Optional[str],
    ) -> None:
        if synth_top is not None:
            if self._parent is not None:
                path = f"{path}.{self._instance_name}" if path else self._instance_name
            else:
                path = self._instance_name

        is_synth = synth_top is not None and (
            path == synth_top or path.startswith(synth_top + ".")
        )
        # On the path leading down to synth_top from above (so a verif
        # parent of a synth descendant is still walked into).
        on_synth_path = synth_top is not None and (
            is_synth or synth_top.startswith(path + ".")
        )

        fname = self._outfile_name
        if fname is not None:
            # Skipping the recursion is safe because shared `fname` implies
            # shared `_sub_instances` (clones via `_new_as_clone`).
            if is_synth and fname in synth_files:
                return
            if (not is_synth) and fname in verif_files and not on_synth_path:
                return
            if is_synth:
                synth_files.add(fname)
            else:
                verif_files.add(fname)

        # clone: descend through _clone_of for traversal -- the clone owns
        # no children, but its source's _sub_instances reflects the shared
        # underlying module's elaborated tree.
        descend = self._sub_instances
        if not descend and self._clone_of is not None:
            descend = self._clone_of._sub_instances
        for sub in descend.values():
            sub._collect_prod_list(results, synth_files, verif_files, path, synth_top)

        results.append((self, is_synth))

    def get_parent(self) -> "UniqueModule | None":
        return self._parent

    def get_top(self) -> "UniqueModule":
        node: UniqueModule = self
        while node._parent is not None:
            node = node._parent
        return node

    # ----------------------------------------------------------- diagnostics
    def to_string(self, *args: Any) -> str:
        """Serialise one or more structures to a printable string.

        Mirrors Perl ``to_string`` (UniqueModule.pm:2911). Uses
        :func:`pprint.pformat` per argument; not a byte-for-byte port
        of Perl's ``CfgHandler::PrintToString`` but covers the
        documented "debug-print arbitrary structures" use case.
        """
        if not args:
            raise ParameterError(
                f"{self._module_name}->to_string: "
                f"expected at least one argument"
            )
        return "\n".join(pprint.pformat(a) for a in args)

    def error(self, msg: str) -> None:
        """Raise a fatal error tagged with this module's identity.

        Mirrors Perl ``$self->error(msg)`` / bare ``error(msg)`` in `.vpy`
        bodies (UniqueModule.pm:2803): the user's message is prefixed with
        the current module and instance path so the failure points at the
        source of the elaboration error.
        """
        reporting.error(
            f"{self._module_name}@{self.get_instance_path()}: {msg}",
            fatal=True,
        )

    def warning(self, msg: str) -> None:
        """Emit a non-fatal warning tagged with this module's identity.

        Mirrors Perl ``$self->warning(msg)`` / bare ``warning(msg)``
        (UniqueModule.pm:2863).
        """
        reporting.warning(
            f"{self._module_name}@{self.get_instance_path()}: {msg}"
        )

    # ----------------------------------------------------------- emission
    def emit(self, text: str) -> None:
        if self._outfile_handle is None:
            self._outfile_handle = io.StringIO()
        self._outfile_handle.write(text + "\n")

    def _emit_comment_block(self, lines: List[str]) -> None:
        """Emit ``lines`` as one comment block in ``manager.output_comment`` style.

        A ``str`` style prefixes every line; an ``(open, close)`` tuple emits
        the delimiters on their own whole lines with the payload indented one
        space. Both shapes are required by :func:`_comparable_lines`, which
        strips comments for structural diffing and keys on whole-line
        delimiters.
        """
        style = getattr(self._manager, "output_comment", "//")
        if isinstance(style, tuple):
            open_d, close_d = style
            self.emit(open_d)
            for ln in lines:
                self.emit(f" {ln}")
            self.emit(close_d)
        else:
            for ln in lines:
                self.emit(f"{style} {ln}")

    def emit_param_footer(self) -> None:
        """Append a resolved-parameter provenance block after the module body.

        No-op unless ``manager.param_footer`` is set (``--param-footer``) and
        this module has at least one parameter. Called from the tail of every
        generated ``execute()`` (``template/emitter.CLASS_BODY_TAIL``) after
        the user body and before the final ``_flush_outfile()``, so the block
        lands at the end of the file, past ``endmodule``. Unlike the
        ``to_verilog`` banner -- written before the body runs -- it sees the
        fully resolved parameter set.

        The flag is read off the manager at runtime rather than baked into the
        generated ``.py`` so that a ``--gen-only`` rerun against a stale
        ``raw_dir`` honours the flag it was given, not the one that produced
        the intermediate.

        The rendered lines deliberately separate name from value with ``:``,
        not ``=``: ``tests/_parity_normalize.py`` scans generated files for
        ``// NAME = value`` banner rows, and its window is unbounded on files
        with no ``module`` keyword.
        """
        if not getattr(self._manager, "param_footer", False):
            return
        if not self._params:
            return
        names = sorted(self._params)
        vals = {n: repr(self._params[n]["value"]) for n in names}
        name_w = max(len(n) for n in names)
        # Cap the value column: one long repr (a list or dict parameter) would
        # otherwise pad every other row out to its width. Values past the cap
        # run long rather than being truncated -- a truncated value would lie.
        val_w = min(max(len(v) for v in vals.values()), _PARAM_FOOTER_VALUE_WIDTH)
        lines = ["Genesis-Py resolved parameter provenance"]
        lines += [
            f"  {n:<{name_w}} : {vals[n]:<{val_w}}  <- "
            f"{_param_provenance(self._params[n])}"
            for n in names
        ]
        self._emit_comment_block(lines)

    def to_verilog(self, infile: Optional[str] = None) -> None:
        """Emit a comment banner + parameter table (parity with :2927).

        Style comes from ``manager.output_comment`` via
        :meth:`_emit_comment_block`.
        """
        lines = [
            f"Genesis-Py generated module: {self._unique_module_name}",
            f"Source class: {self._module_name}",
        ]
        if infile is not None:
            lines.append(f"Source file: {infile}")
        if self._params:
            lines.append("Parameters:")
            for k in sorted(self._params):
                lines.append(f"  {k} = {self._params[k]['value']!r}")
        self._emit_comment_block(lines)

    def _execute_child(self, child: "UniqueModule") -> None:
        """Run ``child.execute()`` with the user-config context bound to the
        child, so ``include()`` and other bare-name helpers inside the child's
        body resolve ``self`` to the child (not the parent under elaboration).
        Mirrors the top-level ``with user_config.context(...)`` in
        ``Manager.gen_verilog``.
        """
        from . import user_config

        # The child may not touch its parent's parameters (UniqueModule.pm:833).
        parent_open = self._params_open
        self._params_open = False
        try:
            with user_config.context(self._manager, child):
                child.execute()
        finally:
            self._params_open = parent_open
            child._params_open = False
        child._lock_params()

    def execute(self) -> None:
        """Elaborate this module: open buffer, emit header, flush.

        Generated subclasses (template/emitter._header) call ``super().execute()``
        for the banner + initial flush, then run user body, then re-flush via
        ``_flush_outfile()`` in the footer. The double-flush is intentional:
        plain subclasses (e.g. tests) rely on the base flush; generated bodies
        need to overwrite with body content.
        """
        if self._outfile_handle is None:
            self._outfile_handle = io.StringIO()
        self.to_verilog()
        self._flush_outfile()

    def _flush_outfile(self) -> None:
        """Write current buffer contents to OUTFILE_CONTENT_CACHE under
        ``_unique_module_name`` and every registered synonym name.
        """
        if self._outfile_handle is None:
            return
        suffix = type(self)._OUTPUT_SUFFIX
        self._outfile_name = f"{self._unique_module_name}{suffix}"
        content = self._outfile_handle.getvalue()
        cache.OUTFILE_CONTENT_CACHE[self._outfile_name] = content
        for syn in self._synonyms:
            cache.OUTFILE_CONTENT_CACHE[f"{syn}{suffix}"] = content

